/**
 * Pulls the handful of icons the game uses out of @iconify-json/game-icons
 * (game-icons.net, CC BY 3.0) into a small committed module, so the app ships
 * ~30 path strings instead of a 4000-icon dataset.
 *
 * Run with: node scripts/extract-icons.mjs
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const iconSet = require('@iconify-json/game-icons/icons.json');
const outFile = join(dirname(dirname(fileURLToPath(import.meta.url))), 'src', 'assets', 'gameIcons.ts');

/** Local name -> game-icons.net icon name. */
const ICONS = {
  // Ores — one clearly different silhouette per ore, so a glance at the grid
  // is enough to tell what is being mined.
  dirt: 'ground-sprout',
  stone: 'stone-block',
  coal: 'coal-pile',
  copper: 'ore',
  iron: 'metal-bar',
  silver: 'minerals',
  goldOre: 'gold-nuggets',
  emerald: 'emerald',
  ruby: 'fire-gem',
  sapphire: 'crystal-shine',
  diamond: 'cut-diamond',
  obsidian: 'rock',
  mythril: 'metal-plate',
  amethyst: 'amethyst',
  crystalCore: 'mineral-heart',
  // Tools and strike feedback
  pickaxe: 'mining',
  warPick: 'war-pick',
  helmet: 'mining-helmet',
  cave: 'cave-entrance',
  // Drones
  drill: 'drill',
  robot: 'tracked-robot',
  drone: 'delivery-drone',
  mech: 'battle-mech',
  ai: 'artificial-intelligence',
  // Currencies
  coins: 'coins',
  gems: 'gems',
  trophy: 'trophy',
  // Gold upgrade tracks
  fist: 'fist',
  clover: 'clover',
  cog: 'cog',
  backpack: 'backpack',
  wagon: 'mine-wagon',
  radar: 'radar-sweep',
  // Gem upgrade tracks
  biceps: 'biceps',
  goldStack: 'gold-stack',
  blast: 'magnet-blast',
  antennas: 'robot-antennas',
  hourglass: 'hourglass',
  sparkles: 'sparkles',
  // Boosts
  fire: 'fire',
  crown: 'crown',
  eagle: 'eagle-emblem',
  // Navigation
  cart: 'shopping-cart',
  upgrade: 'upgrade',
  elevator: 'elevator',
};

const entries = [];
for (const [key, iconName] of Object.entries(ICONS)) {
  const icon = iconSet.icons[iconName];
  if (!icon) throw new Error(`Missing icon in set: ${iconName}`);
  const paths = [...icon.body.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`No path data for: ${iconName}`);
  const unsupported = [...icon.body.matchAll(/<([a-zA-Z]+)/g)].map((m) => m[1]).filter((t) => t !== 'path');
  if (unsupported.length) throw new Error(`${iconName} uses unsupported tags: ${unsupported.join(',')}`);
  entries.push({ key, iconName, width: icon.width ?? iconSet.width, height: icon.height ?? iconSet.height, paths });
}

const size = entries[0].width;
if (entries.some((e) => e.width !== size || e.height !== size)) {
  throw new Error('Icons have mixed viewBox sizes; the renderer assumes one square viewBox.');
}

const body = entries
  .map((e) => `  // game-icons.net: ${e.iconName}\n  ${e.key}: [\n${e.paths.map((p) => `    '${p}',`).join('\n')}\n  ],`)
  .join('\n');

writeFileSync(
  outFile,
  `// GENERATED by scripts/extract-icons.mjs — do not edit by hand.
// Source: game-icons.net via @iconify-json/game-icons, licensed CC BY 3.0.
// Authors are credited in CREDITS.md.

export const ICON_VIEWBOX = ${size};

export const GAME_ICONS = {
${body}
} as const;

export type GameIconName = keyof typeof GAME_ICONS;
`
);

console.log(`Wrote ${entries.length} icons to ${outFile}`);
